[package]
name = "kameo-snake-handler"
version = "0.1.0"
edition = "2021"
authors = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
futures = { workspace = true }
kameo = { workspace = true }
kameo-child-process = { path = "../kameo-child-process" }
kameo_macros = { workspace = true }
pyo3 = { workspace = true }
pyo3-async-runtimes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
kameo-snake-testing = { path = "../kameo-snake-testing" }
proptest = { workspace = true }
tokio-test = "0.4"
