[package]
name = "kameo-snake-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
kameo = { workspace = true }
kameo-child-process = { path = "../kameo-child-process" }
kameo_macros = { workspace = true }
pyo3 = { version = "0.25.1", features = ["auto-initialize"] }
pyo3-async-runtimes = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { workspace = true }
tracing = "0.1"
anyhow = "1.0"
async-trait = "0.1"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }

[dev-dependencies]
kameo-snake-testing = { path = "../kameo-snake-testing" }
proptest = { workspace = true }
tokio-test = "0.4"
