[package]
name = "kameo-child-process"
version = "0.1.0"
edition = "2024"

[dependencies]
kameo = "0.16"
bincode = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
ipc-channel = "0.20.0"
tokio = { version = "1", features = ["full"] }
base64 = "0.22.1"
uuid = "1.17.0"
tracing = "*"
tracing-subscriber = "*"
